const CATEGORY_LABELS = {
  grains: '主食',
  vegetables: '蔬菜',
  fruits: '水果',
  meat_low_fat: '低脂蛋白',
  meat_mid_fat: '中脂蛋白',
  soy: '豆制品',
  dairy: '乳制品',
  nuts: '坚果油脂'
};

const FOOD_LABELS = {
  rice: '大米',
  brown_rice: '糙米',
  oats: '燕麦',
  buckwheat: '荞麦',
  quinoa: '藜麦',
  steamed_bun: '馒头',
  sweet_potato: '红薯',
  corn: '玉米',
  potato: '土豆',
  pumpkin: '南瓜',
  red_beans: '红豆',
  mung_beans: '绿豆',
  tomato: '番茄',
  cucumber: '黄瓜',
  broccoli: '西兰花',
  cauliflower: '菜花',
  cabbage: '卷心菜',
  spinach: '菠菜',
  bok_choy: '小白菜',
  kale: '羽衣甘蓝',
  amaranth: '苋菜',
  mustard_greens: '芥菜',
  carrot: '胡萝卜',
  shiitake: '香菇',
  shiitake_sun: '干香菇',
  enoki: '金针菇',
  wood_ear: '木耳',
  kelp: '海带',
  seaweed: '紫菜',
  onion: '洋葱',
  green_pepper: '青椒',
  bell_pepper: '彩椒',
  you_cai: '油菜',
  baby_napa_cabbage: '娃娃菜',
  konjac: '魔芋',
  celtuce: '莴笋',
  zucchini: '西葫芦',
  strawberry: '草莓',
  cherry_tomato: '圣女果',
  pomelo: '柚子',
  blueberry: '蓝莓',
  kiwi: '猕猴桃',
  pineapple: '菠萝',
  chicken_breast: '鸡胸肉',
  chicken_thigh_skinless: '去皮鸡腿',
  pork_tenderloin: '猪里脊',
  cod: '鳕鱼',
  sea_bass: '鲈鱼',
  tilapia: '罗非鱼',
  basa_fish: '巴沙鱼/龙利鱼',
  shrimp: '虾仁',
  egg_white: '蛋清',
  whole_egg: '鸡蛋',
  egg_yolk: '蛋黄',
  beef_tenderloin: '牛里脊',
  lamb: '羊肉',
  chicken_liver: '鸡肝',
  salmon: '三文鱼',
  hairtail: '带鱼',
  mackerel: '青花鱼/鲐鱼',
  sardine: '沙丁鱼',
  oyster: '生蚝',
  clam: '蛤蜊',
  mussel: '贻贝',
  scallop: '扇贝',
  dried_shrimp: '虾皮',
  tofu_firm: '老豆腐',
  tofu_soft: '嫩豆腐',
  dried_tofu: '豆腐干',
  soy_milk: '豆浆',
  natto: '纳豆',
  edamame: '毛豆',
  black_beans: '黑豆',
  milk: '牛奶',
  yogurt: '酸奶',
  greek_yogurt: '希腊酸奶',
  nut_mix: '混合坚果',
  chia_seed: '奇亚籽',
  sesame: '芝麻',
  sesame_paste: '芝麻酱',
  olive_oil: '橄榄油',
  cooking_oil: '烹调油'
};

function categoryLabel(key) {
  return CATEGORY_LABELS[key] || key;
}

function foodLabel(key) {
  return FOOD_LABELS[key] || key;
}

module.exports = {
  CATEGORY_LABELS,
  FOOD_LABELS,
  categoryLabel,
  foodLabel
};
